# $Id$


REMOTE_HOST=landialler.sourceforge.net
REMOTE_DIR=/home/groups/l/la/landialler/htdocs
REMOTE_USER=ashtong


upload:
	@echo Uploading files to $(REMOTE_HOST) ...
	scp -r * $(REMOTE_USER)@$(REMOTE_HOST):$(REMOTE_DIR)